<?php

namespace App\Helpers\Facades;

use Illuminate\Support\Facades\Facade;

class HelperFD extends Facade
{
    public static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'HelpFD';
    }
}